# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-30 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
